create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table public.competitions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  start_date date not null,
  end_date date not null,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint competitions_dates_check check (end_date >= start_date)
);

create table public.competition_members (
  competition_id uuid not null references public.competitions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  created_at timestamptz not null default now(),
  primary key (competition_id, user_id)
);

create table public.daily_logs (
  id bigint generated by default as identity primary key,
  competition_id uuid not null references public.competitions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null default current_date,
  workout_minutes integer not null default 0 check (workout_minutes >= 0),
  steps integer not null default 0 check (steps >= 0),
  fruit text not null default '',
  vegetable text not null default '',
  dessert text not null default '',
  junk_food text not null default '',
  water_ml integer not null default 0 check (water_ml >= 0),
  sleep_hours numeric(4, 1) not null default 0 check (sleep_hours >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (competition_id, user_id, log_date)
);

alter table public.profiles enable row level security;
alter table public.competitions enable row level security;
alter table public.competition_members enable row level security;
alter table public.daily_logs enable row level security;

create or replace function public.is_competition_member(target_competition_id uuid, target_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.competition_members
    where competition_id = target_competition_id
      and user_id = target_user_id
  );
$$;

create or replace function public.is_competition_owner(target_competition_id uuid, target_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.competitions
    where id = target_competition_id
      and created_by = target_user_id
  );
$$;

create policy "Users can read their profile"
on public.profiles for select
using (id = (select auth.uid()));

create policy "Users can create their profile"
on public.profiles for insert
with check (id = (select auth.uid()));

create policy "Users can update their profile"
on public.profiles for update
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy "Members can read their competitions"
on public.competitions for select
using (
  created_by = (select auth.uid())
  or public.is_competition_member(id, (select auth.uid()))
);

create policy "Users can create competitions"
on public.competitions for insert
with check (created_by = (select auth.uid()));

create policy "Owners can update competitions"
on public.competitions for update
using (created_by = (select auth.uid()))
with check (created_by = (select auth.uid()));

create policy "Members can read competition membership"
on public.competition_members for select
using (
  user_id = (select auth.uid())
  or public.is_competition_owner(competition_id, (select auth.uid()))
);

create policy "Owners can add competition members"
on public.competition_members for insert
with check (
  public.is_competition_owner(competition_id, (select auth.uid()))
);

create policy "Users can read competition logs"
on public.daily_logs for select
using (
  user_id = (select auth.uid())
  or public.is_competition_member(competition_id, (select auth.uid()))
);

create policy "Users can create their own logs"
on public.daily_logs for insert
with check (
  user_id = (select auth.uid())
  and public.is_competition_member(competition_id, (select auth.uid()))
);

create policy "Users can update their own logs"
on public.daily_logs for update
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create policy "Users can delete their own logs"
on public.daily_logs for delete
using (user_id = (select auth.uid()));
